// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA5s_KgR8HHsYD70nLzcCPWIUjI7kJjoZ4',
    appId: '1:149038939122:web:4580f928be15a1c95d096b',
    messagingSenderId: '149038939122',
    projectId: 'sixth-e93da',
    authDomain: 'sixth-e93da.firebaseapp.com',
    storageBucket: 'sixth-e93da.firebasestorage.app',
    measurementId: 'G-ZMEYMPZY3E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBunmmPWAb_SFz7UQ4Dy44T8x-CFicbMjk',
    appId: '1:149038939122:android:c89af49e393095e15d096b',
    messagingSenderId: '149038939122',
    projectId: 'sixth-e93da',
    storageBucket: 'sixth-e93da.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCJL7sRCTmuTyZKoANc4gf5FCcWaCs6JOQ',
    appId: '1:149038939122:ios:eace6616e2da934c5d096b',
    messagingSenderId: '149038939122',
    projectId: 'sixth-e93da',
    storageBucket: 'sixth-e93da.firebasestorage.app',
    iosBundleId: 'com.example.sixthApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCJL7sRCTmuTyZKoANc4gf5FCcWaCs6JOQ',
    appId: '1:149038939122:ios:eace6616e2da934c5d096b',
    messagingSenderId: '149038939122',
    projectId: 'sixth-e93da',
    storageBucket: 'sixth-e93da.firebasestorage.app',
    iosBundleId: 'com.example.sixthApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA5s_KgR8HHsYD70nLzcCPWIUjI7kJjoZ4',
    appId: '1:149038939122:web:40f8fa23943609605d096b',
    messagingSenderId: '149038939122',
    projectId: 'sixth-e93da',
    authDomain: 'sixth-e93da.firebaseapp.com',
    storageBucket: 'sixth-e93da.firebasestorage.app',
    measurementId: 'G-8EC9TLR7B8',
  );

}